#!/bin/bash
CANVAS_HOME="${HTML5_HOME}/canvas"
CANVAS_URL="${HTML5_URL}/canvas"
# using IDL from 
# https://cvs.khronos.org/svn/repos/registry/trunk/public/canvas/doc/spec/canvas.idl
${HTML5_HOME}/parseIDL "${CANVAS_HOME}/index.html" "${CANVAS_HOME}/canvas.idl"
echo '!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/'
echo '!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/'
echo '!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/'
echo '!_TAG_PROGRAM_NAME	Exuberant Ctags	'
echo '!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	'
echo '!_TAG_PROGRAM_VERSION	5.8	//'

${HTML5_HOME}/genTags.pl "${CANVAS_HOME}/canvas.idl" ${CANVAS_HOME}/index.html ${CANVAS_URL}
