#!/bin/bash
./parseIDL
echo '!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/'
echo '!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/'
echo '!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/'
echo '!_TAG_PROGRAM_NAME	Exuberant Ctags	'
echo '!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	'
echo '!_TAG_PROGRAM_VERSION	5.8	//'

./genTags.pl ${HTML5_HOME}/index.html ${HTML5_URL}
