#!/bin/bash
WEBGL_HOME="${HTML5_HOME}/webgl"
WEBGL_URL="${HTML5_URL}/webgl"
# using IDL from 
# https://cvs.khronos.org/svn/repos/registry/trunk/public/webgl/doc/spec/webgl.idl
#./parseIDL "${WEBGL_HOME}/index.html" "${WEBGL_HOME}/webgl.idl"
echo '!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/'
echo '!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/'
echo '!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/'
echo '!_TAG_PROGRAM_NAME	Exuberant Ctags	'
echo '!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	'
echo '!_TAG_PROGRAM_VERSION	5.8	//'

${HTML5_HOME}/genTags.pl "${WEBGL_HOME}/webgl.idl" ${WEBGL_HOME}/index.html ${WEBGL_URL}
