#!/bin/bash
#this must be run from same dir as other files
if [ -z $1 ];then
	echo "need first argument to parseIDL: spec file"
	exit 1
fi
if [ -z $2 ];then
	echo "need second argument to parseIDL: IDL output"
	exit 1
fi
SPEC_FILE=$1
TMP_FILE="$HTML5_HOME/tmp.html"
IDL_FILE=$2

#pre-process file 
${HTML5_HOME}/stripComments.pl $SPEC_FILE | sed -E 's/<pre class="idl"/\
<pre class="idl"/gI' | sed -E 's/<\/pre>/\
<\/pre>/gI' > $TMP_FILE

#extract IDL into output file
${HTML5_HOME}/parseIDL.pl $TMP_FILE > $IDL_FILE

rm $TMP_FILE
